[package]
name = "sum_atp_oracle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1-sys = "0.8.1"
secp256k1-zkp = { version = "0.9.2", features = ["rand-std"] }